// AUTO-GENERATED by `pnpm i18n:extract`. Do not edit by hand —
// re-run the extractor whenever a locale is added or removed in
// `apps/readest-app/i18n-langs.json`. The runtime in
// `src/lib/i18n.ts` reads the bundle map exported from this file.

type Messages = Record<string, string>;

import arMessages from './ar.json';
import bnMessages from './bn.json';
import boMessages from './bo.json';
import deMessages from './de.json';
import elMessages from './el.json';
import enMessages from './en.json';
import esMessages from './es.json';
import faMessages from './fa.json';
import frMessages from './fr.json';
import heMessages from './he.json';
import hiMessages from './hi.json';
import huMessages from './hu.json';
import idMessages from './id.json';
import itMessages from './it.json';
import jaMessages from './ja.json';
import koMessages from './ko.json';
import msMessages from './ms.json';
import nlMessages from './nl.json';
import plMessages from './pl.json';
import ptMessages from './pt.json';
import ptBRMessages from './pt-BR.json';
import roMessages from './ro.json';
import ruMessages from './ru.json';
import siMessages from './si.json';
import slMessages from './sl.json';
import svMessages from './sv.json';
import taMessages from './ta.json';
import thMessages from './th.json';
import trMessages from './tr.json';
import ukMessages from './uk.json';
import uzMessages from './uz.json';
import viMessages from './vi.json';
import zhCNMessages from './zh-CN.json';
import zhTWMessages from './zh-TW.json';

export const bundles: Record<string, Messages> = {
  ar: arMessages as Messages,
  bn: bnMessages as Messages,
  bo: boMessages as Messages,
  de: deMessages as Messages,
  el: elMessages as Messages,
  en: enMessages as Messages,
  es: esMessages as Messages,
  fa: faMessages as Messages,
  fr: frMessages as Messages,
  he: heMessages as Messages,
  hi: hiMessages as Messages,
  hu: huMessages as Messages,
  id: idMessages as Messages,
  it: itMessages as Messages,
  ja: jaMessages as Messages,
  ko: koMessages as Messages,
  ms: msMessages as Messages,
  nl: nlMessages as Messages,
  pl: plMessages as Messages,
  pt: ptMessages as Messages,
  'pt-BR': ptBRMessages as Messages,
  ro: roMessages as Messages,
  ru: ruMessages as Messages,
  si: siMessages as Messages,
  sl: slMessages as Messages,
  sv: svMessages as Messages,
  ta: taMessages as Messages,
  th: thMessages as Messages,
  tr: trMessages as Messages,
  uk: ukMessages as Messages,
  uz: uzMessages as Messages,
  vi: viMessages as Messages,
  'zh-CN': zhCNMessages as Messages,
  'zh-TW': zhTWMessages as Messages,
};
