name: Update Nix Dependencies

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  nix-flake-update:
    permissions:
      contents: write
      id-token: write
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:      
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
      - uses: DeterminateSystems/determinate-nix-action@527f17dd63d2d60d3e5552934bc84b9a33a14d11
      - uses: DeterminateSystems/update-flake-lock@f21d5f4a9e57815a4941a2e7c3860f4664cb3a96
        with:
          pr-title: "chore(nix): update flake inputs"
          pr-labels: |
            dependencies
            automated